###
GET http://localhost:8080/swagger/


###
GET http://localhost:8080/user/get/12


###
POST http://localhost:8080/user/register
Content-Type: application/json

{
  "biography": "Хобби, интересы и т.п.",
  "birthdate": "2017-02-01",
  "city": "Москва",
  "first_name": "Имя",
  "password": "Секретная строка",
  "second_name": "Фамилия"
}


###
POST http://localhost:8080/login
Content-Type: application/json

{
  "id": "string",
  "password": "Секретная строка"
}
